// Generated by tools/generate_game_versions.py; edit game_versions.json.
namespace Fable2Launcher.Constants;
public sealed record GameVersion(string Id, string Hash, string Name, bool Compatible,
    string Reason, int Language, string CodeGroup, string[] RequiredFiles,
    string[] RejectFiles, string[] RejectDirectories);
public static class GameVersions
{
    public const string DefaultProfile = "goty-us-eu";
    public const string CompatibleProfile = "goty-compatible";
    public const string CodeGroup = "goty-identical-payload-2026-09-28";
    public static readonly GameVersion[] All = [
        new("goty-us-eu", "88c4ef2e18e65409444d1b068eff921d1f7e180a5ae64edc64ba6b0872372662", "GOTY USA/Europe", true, "Original GOTY USA/Europe executable and content detected.", 1, "goty-identical-payload-2026-09-28", ["data/gold_version.txt", "data/startup.vfsconfig"], ["data/tu1_data.bnk"], ["data/language/de-de"]),
        new("goty-german", "3f36e7870a06e04b3702760e93c61b1c7fded321b94021da6bfa120b424e6eb4", "German GOTY", true, "Original German GOTY executable and localization detected.", 3, "goty-identical-payload-2026-09-28", ["data/gold_version.txt", "data/startup.vfsconfig", "data/language/de-de/text/book.babel"], ["data/tu1_data.bnk"], ["data/language/de-de"]),
        new("german-retail-tu1", "cec9238ef5d7b391345a8897ef00a4673ae4f106f89385c81723ba5f9d0807b5", "German retail/TU1", false, "German retail/TU1 needs its own validated recompilation profile and is not supported yet.", 3, "unverified", [], [], []),
    ];
}
