// Generated by tools/generate_game_versions.py; edit game_versions.json.
#pragma once
#include <array>
#include <span>
#include <string_view>
namespace fable2::versions {
struct GameVersion {
  std::string_view id, hash, name; bool compatible;
  std::string_view reason; int language; std::string_view code_group;
  std::span<const std::string_view> required_files, reject_files, reject_directories;
};
inline constexpr std::string_view kDefaultProfile = "goty-us-eu";
inline constexpr std::string_view kCompatibleProfile = "goty-compatible";
inline constexpr std::string_view kCodeGroup = "goty-identical-payload-2026-09-28";
inline constexpr std::array<std::string_view, 2> krequiredFiles0 = {"data/gold_version.txt", "data/startup.vfsconfig"};
inline constexpr std::array<std::string_view, 1> krejectFiles0 = {"data/tu1_data.bnk"};
inline constexpr std::array<std::string_view, 1> krejectDirectories0 = {"data/language/de-de"};
inline constexpr std::array<std::string_view, 3> krequiredFiles1 = {"data/gold_version.txt", "data/startup.vfsconfig", "data/language/de-de/text/book.babel"};
inline constexpr std::array<std::string_view, 1> krejectFiles1 = {"data/tu1_data.bnk"};
inline constexpr std::array<std::string_view, 1> krejectDirectories1 = {"data/language/de-de"};
inline constexpr std::array<std::string_view, 0> krequiredFiles2 = {};
inline constexpr std::array<std::string_view, 0> krejectFiles2 = {};
inline constexpr std::array<std::string_view, 0> krejectDirectories2 = {};
inline constexpr std::array<GameVersion, 3> kVersions = {{
  {"goty-us-eu", "88c4ef2e18e65409444d1b068eff921d1f7e180a5ae64edc64ba6b0872372662", "GOTY USA/Europe", true, "Original GOTY USA/Europe executable and content detected.", 1, "goty-identical-payload-2026-09-28", krequiredFiles0, krejectFiles0, krejectDirectories0},
  {"goty-german", "3f36e7870a06e04b3702760e93c61b1c7fded321b94021da6bfa120b424e6eb4", "German GOTY", true, "Original German GOTY executable and localization detected.", 3, "goty-identical-payload-2026-09-28", krequiredFiles1, krejectFiles1, krejectDirectories1},
  {"german-retail-tu1", "cec9238ef5d7b391345a8897ef00a4673ae4f106f89385c81723ba5f9d0807b5", "German retail/TU1", false, "German retail/TU1 needs its own validated recompilation profile and is not supported yet.", 3, "unverified", krequiredFiles2, krejectFiles2, krejectDirectories2},
}};
inline constexpr const GameVersion* Find(std::string_view hash) {
  for (const auto& version : kVersions) if (version.hash == hash) return &version;
  return nullptr;
}
}  // namespace fable2::versions
