"""Generate shared C#/C++/CMake constants from the source-only version catalogue.

Run after editing constants/game_versions.json; --check rejects stale outputs.
No original game content is required. Generated files are tracked so native
standalone tests and .NET builds need no runtime JSON/parser dependency.
"""
import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def generate():
    catalog = json.loads((ROOT / "constants/game_versions.json").read_text(encoding="utf-8"))
    versions = catalog["versions"]
    ids, hashes = set(), set()
    for v in versions:
        if not re.fullmatch(r"[a-z0-9-]+", v["id"]) or v["id"] in ids:
            raise ValueError("Invalid/duplicate version ID")
        if not re.fullmatch(r"[0-9a-f]{64}", v["hash"]) or v["hash"] in hashes:
            raise ValueError("Invalid/duplicate SHA-256")
        if type(v["compatible"]) is not bool or not v["name"] or not v["reason"]:
            raise ValueError("Each version needs a name, compatibility boolean and reason")
        # SDK XLanguage: kEnglish=1 through kRussian=12; 13 is the sentinel.
        if type(v["language"]) is not int or not 1 <= v["language"] <= 12:
            raise ValueError("Invalid Xbox language ID")
        for key in ("requiredFiles", "rejectFiles", "rejectDirectories"):
            if not isinstance(v[key], list):
                raise ValueError("Marker lists must be arrays")
            for path in v[key]:
                if not isinstance(path, str) or not path or path.startswith("/") or ":" in path or "\\" in path or any(part in ("", ".", "..") for part in path.split("/")):
                    raise ValueError("Markers must be relative POSIX paths")
        ids.add(v["id"])
        hashes.add(v["hash"])
    default = next(v for v in versions if v["id"] == catalog["defaultProfile"])
    if not default["compatible"] or default["codeGroup"] != catalog["codeGroup"]:
        raise ValueError("Default version must belong to the validated guest-code group")
    quote = lambda s: json.dumps(s, ensure_ascii=True)
    cs_array = lambda values: "[" + ", ".join(map(quote, values)) + "]"
    cpp = ['// Generated by tools/generate_game_versions.py; edit game_versions.json.',
           '#pragma once', '#include <array>', '#include <span>', '#include <string_view>',
           'namespace fable2::versions {',
           'struct GameVersion {',
           '  std::string_view id, hash, name; bool compatible;',
           '  std::string_view reason; int language; std::string_view code_group;',
           '  std::span<const std::string_view> required_files, reject_files, reject_directories;',
           '};']
    cs = ['// Generated by tools/generate_game_versions.py; edit game_versions.json.',
          'namespace Fable2Launcher.Constants;',
          'public sealed record GameVersion(string Id, string Hash, string Name, bool Compatible,',
          '    string Reason, int Language, string CodeGroup, string[] RequiredFiles,',
          '    string[] RejectFiles, string[] RejectDirectories);',
          'public static class GameVersions', '{']
    cmake = ['# Generated by tools/generate_game_versions.py; edit game_versions.json.']
    for json_key, cpp_key, cs_key in (("defaultProfile", "kDefaultProfile", "DefaultProfile"),
                                     ("compatibleProfile", "kCompatibleProfile", "CompatibleProfile"),
                                     ("codeGroup", "kCodeGroup", "CodeGroup")):
        cpp.append(f'inline constexpr std::string_view {cpp_key} = {quote(catalog[json_key])};')
        cs.append(f'    public const string {cs_key} = {quote(catalog[json_key])};')
    for index, v in enumerate(versions):
        for key in ("requiredFiles", "rejectFiles", "rejectDirectories"):
            cpp.append(f'inline constexpr std::array<std::string_view, {len(v[key])}> k{key}{index} = '
                       + '{' + ', '.join(map(quote, v[key])) + '};')
    cpp.append(f'inline constexpr std::array<GameVersion, {len(versions)}> kVersions = {{{{')
    cs.append('    public static readonly GameVersion[] All = [')
    for index, v in enumerate(versions):
        fields = [quote(v[k]) for k in ("id", "hash", "name")]
        fields += [str(v["compatible"]).lower(), quote(v["reason"]), str(v["language"]), quote(v["codeGroup"])]
        cpp.append('  {' + ', '.join(fields + [f'k{key}{index}' for key in ("requiredFiles", "rejectFiles", "rejectDirectories")]) + '},')
        cs.append('        new(' + ', '.join(fields + [cs_array(v[key]) for key in ("requiredFiles", "rejectFiles", "rejectDirectories")]) + '),')
        if v["compatible"] and v["codeGroup"] == catalog["codeGroup"]:
            cmake += [f'list(APPEND FABLE2_CATALOG_PROFILES {quote(v["id"])})',
                      f'set(FABLE2_CATALOG_HASH_{v["id"]} {quote(v["hash"])})',
                      f'set(FABLE2_CATALOG_LANGUAGE_{v["id"]} {v["language"]})']
    cpp += ['}};', 'inline constexpr const GameVersion* Find(std::string_view hash) {',
            '  for (const auto& version : kVersions) if (version.hash == hash) return &version;',
            '  return nullptr;', '}', '}  // namespace fable2::versions']
    cs += ['    ];', '}']
    cmake += [f'set(FABLE2_CATALOG_DEFAULT_PROFILE {quote(catalog["defaultProfile"])})',
              f'set(FABLE2_CATALOG_COMPATIBLE_PROFILE {quote(catalog["compatibleProfile"])})',
              f'set(FABLE2_CATALOG_CODE_GROUP {quote(catalog["codeGroup"])})']
    return {"GameVersions.cs": cs, "game_versions.h": cpp, "game_versions.cmake": cmake}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for name, lines in generate().items():
        path = ROOT / "constants" / name
        content = "\n".join(lines) + "\n"
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                raise SystemExit(f"Stale constants: {name}; run python tools/generate_game_versions.py")
        else:
            path.write_text(content, encoding="utf-8", newline="\n")
    print("Shared game-version constants are up to date.")


if __name__ == "__main__":
    main()
